dataset_dir: "../datasets/20201124" # dataset directory
task: dn # roi | dn
scan: False # wether to run hyperopt scan
channel: collection # induction | collection
dev: cpu # cpu | cuda:0 | [0,1,2,3]
     # - 0
     # - 1
     # - 2
     # - 3

# model architecture
model: cnn # cnn | gcnn | uscg
load_path: null # path to .pth checkpoint
load_epoch: 100 # load from epoch number from output directory checkpoints
save: True # wether to save checkpoints during training

# trainings
epochs: 1 # number of training epochs
epoch_log: 1 # logging epochs interval
epoch_test_start: 0 # test starting epoch
epoch_test: 1 # test on epoch end interval
loss_fn: ssim_l2 # mse | ssim | ssim_l1 | ssim_l2
a: 0.84 # balancing between loss function contributions (if multiple)
lr: 0.001 # optimizer's learning rate
amsgrad: True # Adam optimizer option
batch_size: 1

# inference
threshold: 3.5 # 500 e- | 3.5 ADC counts (threshold for inference)

# geometry
patch_size: 32
input_channels: 1 # input channels number in (N,C,H,W)
hidden_channels: 32 # (graph) convolution network hidden filters number
