dataset_dir: "../datasets/20201124"

task: "roi" # roi | dn

model: "uscg" # cnn | gcnn | uscg

epochs: 1 # number of training epochs

loss_fn: "mse" # mse | ssim | ssim_l1 | ssim_l2

lr: 0.001

out_name: "202011/scg" # output dirname in denoising/output folder

load_path: None # "denoising/best_models/scg_dn_induction.pth" # torch .dat absolute filepath

threshold: 3.5 # 500 e- | 3.5 ADC counts

amsgrad: True

channel: "collection" # induction | collection

scan: False

patch_w: 2000

patch_h: 960

patch_stride: 1000
