dataset_dir: "../datasets/20201124" # dataset directory
task: dn # roi | dn
scan: False # wether to run hyperopt scan
channel: induction # induction | collection
dev: cpu # cpu | cuda:0 | [0,1,2,3]
     # - 0
     # - 1
     # - 2
     # - 3

# model architecture
model: uscg # cnn | gcnn | uscg
load_path: null # path to .pth checkpoint
load_epoch: 100 # load from epoch number from output directory checkpoints
save: True # wether to save checkpoints during training

# trainings
epochs: 1 # number of training epochs
epoch_log: 1 # logging epochs interval
epoch_test_start: 0 # test starting epoch
epoch_test: 1 # test on epoch end interval
loss_fn: mse # mse | ssim | ssim_l1 | ssim_l2
a: 0.5 # balancing between loss function contributions (if multiple)
lr: 0.001 # optimizer's learning rate
amsgrad: True # Adam optimizer option
batch_size: 1

# inference
threshold: 3.5 # 500 e- | 3.5 ADC counts (threshold for inference)

# geometry
patch_w: 2000 # inference image width
patch_h: 800 # inference image height
patch_stride: 1000 # inference stride
