dataset_dir: "../datasets/denoising"

task: "roi" # roi | dn

model: "cnn" # cnn | gcnn

epochs: 100 # number of training epochs

loss_fn: "ssim_l2" # mse | ssim | ssim_l1 | ssim_l2

lr_dn: 0.009032117010326078

lr_roi: 0.001

out_name: "2011_cnn_roi" # output dirname in denoising/output folder

load_path: None # torch .dat absolute filepath

batch_size: 256

test_batch_size: 256

threshold: 3.5

amsgrad: True

scan: False
