dataset_dir: "../datasets/20201124"

task: "roi" # roi | dn

model: "scg" # cnn | gcnn | scg

epochs: 2 # number of training epochs

loss_fn: "mse" # mse | ssim | ssim_l1 | ssim_l2

lr: 0.001

out_name: "202011/scg" # output dirname in denoising/output folder

load_path: None # "denoising/best_models/scg_dn_induction.pth" # torch .dat absolute filepath

threshold: 500 # 500 e- | 3.5 ADC counts

amsgrad: True

channel: "collection" # induction | collection

scan: False

patch_w: 2000

patch_stride: 1000
